sources:
  - name: source_bronze
    database: pysparkdbt  
    schema: bronze  
    tables:
      - name: trips

  - name: source_silver
    database: pysparkdbt  
    schema: silver  
    tables:
      - name: drivers
      - name: payments
      - name: locations
      - name: customers
      - name: vehicles

  